#pragma once
class Common 
{
public:
	enum ERROR_CODE : short
	{
		NONE = 0,

		UNASSIGNED_ERROR = 201,

		MAIN_INIT_NETWORK_INIT_FAIL = 206,

		USER_MGR_ID_DUPLICATION = 211,
		USER_MGR_MAX_USER_COUNT = 212,
		USER_MGR_INVALID_SESSION_INDEX = 213,
		USER_MGR_NOT_CONFIRM_USER = 214,
		USER_MGR_INVALID_ID = 215,
		USER_MGR_REMOVE_INVALID_SESSION = 221,
	
		LOBBY_LIST_INVALID_DOMAIN = 226,

		LOBBY_ENTER_INVALID_DOMAIN = 231,
		LOBBY_ENTER_INVALID_LOBBY_INDEX = 232,
		LOBBY_ENTER_USER_DUPLICATION = 234,
		LOBBY_ENTER_MAX_USER_COUNT = 235,
		LOBBY_ENTER_EMPTY_USER_LIST = 236,

		LOBBY_ROOM_LIST_INVALID_START_ROOM_INDEX = 241,
		LOBBY_ROOM_LIST_INVALID_DOMAIN = 242,
		LOBBY_ROOM_LIST_INVALID_LOBBY_INDEX = 243,

		LOBBY_USER_LIST_INVALID_DOMAIN = 251,
		LOBBY_USER_LIST_INVALID_LOBBY_INDEX = 252,
		LOBBY_USER_LIST_INVALID_START_USER_INDEX = 253,

		LOBBY_LEAVE_INVALID_DOMAIN = 261,
		LOBBY_LEAVE_INVALID_LOBBY_INDEX = 262,
		LOBBY_LEAVE_USER_NVALID_UNIQUEINDEX = 263,

		ROOM_ENTER_INVALID_DOMAIN = 271,
		ROOM_ENTER_INVALID_LOBBY_INDEX = 272,
		ROOM_ENTER_INVALID_ROOM_INDEX = 273,
		ROOM_ENTER_CREATE_FAIL = 274,
		ROOM_ENTER_NOT_CREATED = 275,
		ROOM_ENTER_MEMBER_FULL = 276,


		ROOM_LEAVE_INVALID_DOMAIN = 286,
		ROOM_LEAVE_INVALID_LOBBY_INDEX = 287,
		ROOM_LEAVE_INVALID_ROOM_INDEX = 288,
		ROOM_LEAVE_NOT_CREATED = 289,
		ROOM_LEAVE_NOT_MEMBER = 290,

		ROOM_CHAT_INVALID_DOMAIN = 296,
		ROOM_CHAT_INVALID_LOBBY_INDEX = 297,
		ROOM_CHAT_INVALID_ROOM_INDEX = 298,

		LOBBY_CHAT_INVALID_DOMAIN = 306,
		LOBBY_CHAT_INVALID_LOBBY_INDEX = 307,

		LOBBY_WHISPER_INVALID_DOMAIN = 310,
		LOBBY_WHISPER_INVALID_LOBBY_INDEX = 311,
	};

	// 21 이상부터 시작해야 한다!!!
	enum PACKET_ID : short
	{
		LOGIN_IN_REQ = 21,
		LOGIN_IN_RES = 22,

		LOGIN_OUT_REQ = 23,
		LOGIN_OUT_RES = 24,

		LOBBY_LIST_REQ = 26,
		LOBBY_LIST_RES = 27,

		LOBBY_ENTER_REQ = 31,
		LOBBY_ENTER_RES = 32,
		LOBBY_ENTER_USER_NTF = 33,

		LOBBY_ENTER_ROOM_LIST_REQ = 41,
		LOBBY_ENTER_ROOM_LIST_RES = 42,

		LOBBY_ENTER_USER_LIST_REQ = 43,
		LOBBY_ENTER_USER_LIST_RES = 44,

		LOBBY_LEAVE_REQ = 46,
		LOBBY_LEAVE_RES = 47,
		LOBBY_LEAVE_USER_NTF = 48,

		ROOM_ENTER_REQ = 61,
		ROOM_ENTER_RES = 62,
		ROOM_ENTER_USER_NTF = 63,

		ROOM_LEAVE_REQ = 66,
		ROOM_LEAVE_RES = 67,
		ROOM_LEAVE_USER_NTF = 68,

		ROOM_CHANGED_INFO_NTF = 71,

		ROOM_CHAT_REQ = 76,
		ROOM_CHAT_RES = 77,
		ROOM_CHAT_NTF = 78,

		LOBBY_CHAT_REQ = 81,
		LOBBY_CHAT_RES = 82,
		LOBBY_CHAT_NTF = 83,
		
		LOBBY_WHISPER_REQ = 91,
		LOBBY_WHISPER_RES = 92,
		LOBBY_WHISPER_NTF = 93,

		NTF_SYS_CLOSE_SESSION = 255,
		MAX = 256
	};

};
